### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by sorenwacker** [alphasecio/langchain-examples#2]
Not sure to which repo this belongs to. I tried the demo 

https://alphasec.io/persistent-ai-chat-bots-with-langchain-and-steamship/

and after `ship deploy` it ends 

> steamship.base.error.SteamshipError: Could not find api.py either in root directory or in src.

**Comment by alphasecio** [comment]
That's right, I just tested it and looks like the `steamship` package is broken. I don't maintain the package though; you'll need to raise an issue here: https://github.com/steamship-core/vercel-examples/tree/main/ai-chatgpt.

FWIW, changing `pip install steamship steamship-langchain` to `pip install steamship=2.3.13 steamship-langchain` (package version in the original demo) works. Sorry, can't help you beyond this.
